### PR TITLE
Clearer documentation 

### PR DESCRIPTION
**Pull request by CarolineMorton**
I have changed a few bits on the documentation and added some pictures, particularly of the bash console. I hope that clarifies the installation of package workflow. 

I don't a windows machine to add in screen shots of the installation process. I've hosted the images on: https://imgbb.com/

### CODE REVIEW

**Comment by sebbacon** [comment]
Looks good to me. By the way when adding images to github-hosted things I use the thing where you paste an image into a new issue, then I copy the markdown it generates, and cancel the issue!

I seem to recall Helen having some other confusion beyond this during Windows install? I think partly there was just too much text. We talked about a separate "installation" document, integrating those notes in that Windows issue I made, for example?

**Comment by CarolineMorton** [comment]
This sounds sensible. You can probably tell i was having a bit of an argument with markdown about images!

I can try to make an installation guide for clarity as INSTALLATION.md i guess. Is that what you were thinking?

**Comment by sebbacon** [comment]
Yes that's what I was thinking :)

**Comment by CarolineMorton** [comment]
Great. i'm going to merge this for now into master, and then branch again so I can work on this. Unless you are working on the master on your machine?

**Pull request merged**
