### PR TITLE
Better port mapping

### LINKED ISSUE #15: Make running on multiple ports easier
Many researchers want to have multiple repos running. The current shell/batch scripts always launch on port 8888

It would be nice for them to automatically find the next available port; or if this is too fiddly, at least to prompt about which port to use.

### PR DESCRIPTION
**Pull request by sebbacon**
Adds a python script (and Windows executable for this script, built via a Github Actions Workflow), to replace current startup.

Main improvement is that you can easily run multiple dockers as ports are mapped for you, and it opens a browser for you on the right port.

Also attempts to tidy things up nicely with signal handlers.

Closes #15

(Have somehow pulled in duplicate commits from master when doing commit surgery)

### CODE REVIEW

**Comment by sebbacon** [comment]
There's an issue where the build-and-commit workflow completes before the notebook tests; this means a new commit is added before the current status is completed, leaving the PR with no pending (or failed or successful) status.

The fix would be to merge the workflows or otherwise make them dependent, i.e. the build happens after the tests.

It would also be nice to make the build step only happen when `run.py` has changed...

**Comment by sebbacon** [comment]
Reviewers: this is best read as a single diff!

**Review by evansd — APPROVED** [review]
This is really cool. I was prepared for something a bit grim and hacky (due to the nature of the problem, I should add!) but other than that annoyance around workflow ordering (which I'm sure will be solvable in the future even if not now) this all looks very nice. It's particularly great that GitHub can automatically build a Windows executable for us. And the `run.py` script itself is a model of clarity.

:+1:

**Review by inglesp — APPROVED** [review]
I agree with Dave.

**Pull request merged**
